a = ('able', 'unable', 'abaxial', 'adaxial', 'acroscopic', 'basiscopic', 'abducent', 'adducent', 'nascent', 'emergent',
     'dissilient', 'parturient', 'dying', 'moribund', 'last', 'abridged', 'cut', 'halfLength', 'potted', 'unabridged',
     'fullLength', 'absolute', 'direct', 'implicit', 'infinite', 'living', 'relative', 'relational', 'absorbent',
     'absorbefacient', 'assimilating', 'hygroscopic', 'receptive', 'shockAbsorbent', 'spongy', 'thirsty',
     'nonabsorbent', 'repellent', 'adsorbent', 'chemisorptive', 'nonadsorbent', 'absorbable', 'adsorbable',
     'abstemious', 'abstinent', 'ascetic', 'gluttonous', 'crapulous', 'crapulent', 'edacious', 'greedy', 'hoggish',
     'overgreedy', 'abstract', 'conceptional', 'conceptual', 'ideal', 'ideological', 'concrete', 'objective', 'real',
     'abundant', 'abounding', 'ample', 'copious', 'easy', 'exuberant', 'thick', 'long', 'overabundant', 'plentiful',
     'rampant', 'rank', 'superabundant', 'teeming', 'torrential', 'verdant', 'scarce', 'rare', 'tight', 'abused',
     'battered', 'unabused', 'acceptable', 'bankable', 'unexceptionable', 'unobjectionable', 'unacceptable',
     'exceptionable', 'accessible', 'approachable', 'comeAtAble', 'handy', 'inaccessible', 'outback', 'pathless',
     'unapproachable', 'unComeAtAble', 'accommodating', 'complaisant', 'unaccommodating', 'disobliging', 'accurate',
     'close', 'deadOn', 'highFidelity', 'surgical', 'straight', 'true', 'veracious', 'inaccurate', 'away', 'faulty',
     'unfaithful', 'wide', 'accustomed', 'usedTo', 'unaccustomed', 'new', 'unused', 'acidic', 'acid', 'acidForming',
     'alkaline', 'alkalescent', 'basic', 'baseForming', 'saltlike', 'amphoteric', 'acidLoving', 'acidophilic',
     'alkalineLoving', 'acknowledged', 'accepted', 'selfConfessed', 'assumptive', 'declarable', 'given', 'putative',
     'unacknowledged', 'unappreciated', 'unavowed', 'unconfessed', 'unrecognized', 'acquisitive', 'accumulative',
     'avaricious', 'possessive', 'plundering', 'predaceous', 'rapacious', 'sordid', 'unacquisitive', 'acropetal',
     'basipetal', 'active', 'about', 'acrobatic', 'agile', 'hot', 'hyperactive', 'onTheGo', 'sporty', 'inactive',
     'deskBound', 'abeyant', 'hypoactive', 'inert', 'sedentary', 'active', 'activated', 'inactive', 'off', 'retired',
     'active', 'brisk', 'bustling', 'busy', 'going', 'open', 'springy', 'inactive', 'dark', 'dead', 'dull', 'idle',
     'strikebound', 'active', 'progressive', 'inactive', 'deadEnd', 'flat', 'indolent', 'latent', 'quiescent', 'active',
     'activist', 'handsOn', 'proactive', 'passive', 'handsOff', 'resistless', 'active', 'eruptive', 'dormant',
     'quiescent', 'extinct', 'dead', 'active', 'alive', 'active', 'stative', 'active', 'passive', 'active', 'activated',
     'counteractive', 'surfaceActive', 'inactive', 'quiescent', 'active', 'quiet', 'actual', 'effective', 'potential',
     'latent', 'acute', 'subacute', 'chronic', 'degenerative', 'virulent', 'highlyInfective', 'deadly', 'avirulent',
     'adaptive', 'accommodative', 'adaptational', 'adjustive', 'maladaptive', 'dysfunctional', 'maladjustive',
     'addicted', 'alcoholic', 'dependent', 'unaddicted', 'clean', 'addictive', 'nonaddictive', 'additive',
     'accumulative', 'addable', 'extra', 'complemental', 'incremental', 'intercalary', 'summational', 'supplementary',
     'subtractive', 'ablative', 'reductive', 'addressed', 'selfAddressed', 'unaddressed', 'adequate', 'adequateTo',
     'competent', 'inadequate', 'deficient', 'incapable', 'shortHanded', 'adhesive', 'adherent', 'agglutinate',
     'bondable', 'coherent', 'cohesive', 'gluey', 'gooey', 'gumLike', 'gummed', 'pitchy', 'selfSealing', 'stickOn',
     'sticky', 'nonadhesive', 'nonglutinous', 'nonresinous', 'ungummed', 'adjective', 'substantive', 'adoptable',
     'unadoptable', 'adorned', 'beady', 'bedaubed', 'bespectacled', 'brocaded', 'buttony', 'carbuncled', 'champleve',
     'clinquant', 'crested', 'crested', 'crested', 'crocketed', 'feathery', 'frilled', 'fringed', 'giltEdged',
     'inflamed', 'inlaid', 'inwrought', 'tessellated', 'mounted', 'paneled', 'studded', 'tapestried', 'tasseled',
     'trickedOut', 'tufted', 'unadorned', 'plain', 'untufted', 'cholinergic', 'anticholinergic', 'adroit', 'clean',
     'clever', 'coordinated', 'deft', 'handy', 'lightFingered', 'quickWitted', 'maladroit', 'bumbling', 'inept',
     'uncoordinated', 'unmechanical', 'advantageous', 'beneficial', 'plus', 'discriminatory', 'disadvantageous',
     'minus', 'adventurous', 'audacious', 'sporting', 'swaggering', 'unadventurous', 'safe', 'advisable', 'better',
     'well', 'inadvisable', 'wellAdvised', 'considered', 'illAdvised', 'aerobic', 'aerobiotic', 'oxidative',
     'anaerobic', 'aerobic', 'anaerobic', 'aesthetic', 'artistic', 'cosmetic', 'painterly', 'sensuous', 'inaesthetic',
     'inartistic', 'affected', 'impressed', 'smitten', 'stageStruck', 'subject', 'taken', 'wonderStruck', 'unaffected',
     'immune', 'superior', 'unimpressed', 'uninfluenced', 'affected', 'agonistic', 'artificial', 'constrained',
     'elocutionary', 'mannered', 'plummy', 'unaffected', 'lifelike', 'unmannered', 'unselfconscious', 'unstilted',
     'affirmative', 'assentient', 'negative', 'dissentient', 'acceptive', 'accepting', 'rejective', 'dismissive',
     'repudiative', 'afloat', 'adrift', 'floating', 'waterborne', 'aground', 'afraid', 'acrophobic', 'afeard', 'aghast',
     'agoraphobic', 'alarmed', 'algophobic', 'apprehensive', 'hangdog', 'claustrophobic', 'fearful', 'frightened',
     'horrified', 'hunted', 'hydrophobic', 'mysophobic', 'panicky', 'numb', 'shitless', 'terrorStricken',
     'triskaidekaphobic', 'unnerved', 'whiteLipped', 'xenophobic', 'unafraid', 'unapprehensive', 'unblinking',
     'unfrightened', 'aggressive', 'battleful', 'competitive', 'hardHitting', 'hostile', 'inYourFace', 'obstreperous',
     'predatory', 'pugnacious', 'scrappy', 'truculent', 'unaggressive', 'lowPressure', 'agitated', 'aroused',
     'distraught', 'jolted', 'feverish', 'frantic', 'hysterical', 'psychedelic', 'wildEyed', 'unagitated', 'agitated',
     'churning', 'churning', 'jolted', 'rippled', 'seething', 'stirred', 'unagitated', 'nonturbulent', 'unstirred',
     'agreeable', 'disagreeable', 'annoying', 'harsh', 'nerveRacking', 'unsweet', 'airToSurface', 'airToAir',
     'surfaceToAir', 'alert', 'argusEyed', 'fly', 'headsUp', 'lidless', 'unalert', 'algorithmic', 'recursive',
     'heuristic', 'trialAndError', 'alienable', 'appropriable', 'assignable', 'inalienable', 'absolute',
     'nonNegotiable', 'nontransferable', 'alive', 'liveborn', 'viable', 'vital', 'dead', 'asleep', 'assassinated',
     'bloodless', 'brainDead', 'breathless', 'cold', 'd.o.a.', 'deathlike', 'defunct', 'doomed', 'executed', 'fallen',
     'late', 'lifeless', 'murdered', 'nonviable', 'slain', 'stillborn',
     'stoneDead', 'apocrine', 'eccrine', 'artesian', 'subartesian', 'live', 'inPlay', 'living', 'dead', 'extinct',
     'lifeless', 'outOfPlay', 'alphabetic', 'abecedarian', 'alphabetized', 'analphabetic', 'altricial', 'precocial',
     'altruistic', 'egoistic', 'selfAbsorbed', 'ambiguous', 'doubleBarreled', 'doubleEdged', 'enigmatic', 'leftHanded',
     'multivalent', 'polysemous', 'uncertain', 'unambiguous', 'monosemous', 'ambitious', 'pushful', 'aspirant',
     'compulsive', 'manque', 'overambitious', 'unambitious', 'shiftless', 'ametropic', 'emmetropic', 'ample', 'full',
     'generous', 'wide', 'meager', 'bare', 'exiguous', 'handToMouth', 'hardscrabble', 'measly', 'anabolic',
     'constructiveMetabolic', 'catabolic', 'destructiveMetabolic', 'anaclinal', 'cataclinal', 'anastigmatic',
     'astigmatic', 'anticlinal', 'synclinal', 'anadromous', 'catadromous', 'diadromous', 'anabatic', 'katabatic',
     'anal', 'oral', 'analogue', 'digital', 'analytic', 'synthetic', 'analytic', 'isolating', 'synthetic',
     'agglutinative', 'analytic', 'synthetic', 'inflectional', 'derivational', 'apocarpous', 'syncarpous', 'angry',
     'aggravated', 'angered', 'black', 'choleric', 'hotUnderTheCollar', 'huffy', 'indignant', 'irate', 'livid',
     'smoldering', 'wrathful', 'unangry', 'resentful', 'acrimonious', 'rancorous', 'unresentful', 'unbitter',
     'sentient', 'sensate', 'insentient', 'unfeeling', 'animate', 'inanimate', 'nonconscious', 'animated', 'enlivened',
     'fullOfLife', 'reanimated', 'unanimated', 'lifeless', 'wan', 'enlivened', 'perkedUp', 'unenlivened', 'animate',
     'inanimate', 'anonymous', 'nameless', 'onymous', 'binomial', 'pseudonymous', 'antemortem', 'postmortem',
     'antecedent', 'anterior', 'anticipatory', 'preexistent', 'subsequent', 'attendant', 'later', 'antrorse',
     'retrorse', 'decurved', 'aquatic', 'marine', 'semiaquatic', 'subaqueous', 'terrestrial', 'onshore', 'overland',
     'amphibious', 'amphibiotic', 'preceding', 'above', 'aboveMentioned', 'foregoing', 'introductory', 'precedent',
     'premedical', 'preparatory', 'previous', 'succeeding', 'backToBack', 'ensuing', 'following', 'following', 'inLine',
     'postmortem', 'precedented', 'unprecedented', 'new', 'prehensile', 'nonprehensile', 'prenatal', 'perinatal',
     'postnatal', 'preprandial', 'postprandial', 'prewar', 'postwar', 'retrograde', 'anterograde', 'antemeridian',
     'anteMeridiem', 'postmeridian', 'postMeridiem', 'anterior', 'frontal', 'frontal', 'prefrontal', 'posterior',
     'back', 'caudal', 'retral', 'dorsal', 'ventral', 'dorsoventral', 'appealable', 'unappealable', 'appendaged',
     'unappendaged', 'appetizing', 'mouthWatering', 'unappetizing', 'approachable', 'accessible', 'unapproachable',
     'offish', 'appropriate', 'befitting', 'gradeAppropriate', 'pat', 'proper', 'inappropriate', 'unbefitting',
     'improper', 'due', 'callable', 'collect', 'collectible', 'delinquent', 'receivable', 'outOfPocket', 'repayable',
     'undue', 'due', 'undue', 'apropos', 'apposite', 'malapropos', 'inapposite', 'aPriori', 'aPosteriori', 'apteral',
     'amphiprostylar', 'prostyle', 'peripteral', 'monopteral', 'peristylar', 'arbitrable', 'nonarbitrable', 'columned',
     'amphistylar', 'columnar', 'columniform', 'colonnaded', 'pillared', 'noncolumned', 'astylar', 'unpillared',
     'arboreal', 'nonarboreal', 'arenaceous', 'argillaceous', 'armed', 'equipped', 'lightArmed', 'militarized',
     'unarmed', 'barehanded', 'clean', 'defenseless', 'weaponless', 'armored', 'armorClad', 'bonyPlated', 'bulletproof',
     'lightlyArmored', 'mailCheeked', 'mailClad', 'scaled', 'unarmored', 'armed', 'barbed', 'bristlelike', 'brushlike',
     'thistlelike', 'clawed', 'unarmed', 'thornless', 'armed', 'armlike', 'brachiate', 'longArmed', 'oneArmed',
     'armless', 'armored', 'boneCovered', 'scaly', 'silverScaled', 'unarmored', 'scaleless', 'artful', 'crafty', 'cute',
     'designing', 'deep', 'elusive', 'manipulative', 'pawky', 'artless', 'careless', 'articulate', 'eloquent',
     'speechEndowed', 'wellSpoken', 'inarticulate', 'aphasic', 'aphonic', 'dumb', 'dumb', 'incoherent', 'mute',
     'speechless', 'unarticulated', 'speaking', 'tongued', 'nonspeaking', 'articulated', 'jointed', 'unarticulated',
     'unjointed', 'ashamed', 'discredited', 'embarrassed', 'guilty', 'shamefaced', 'unashamed', 'audacious',
     'shameless', 'unabashed', 'assertive', 'cocky', 'emphatic', 'unassertive', 'nonassertive', 'reticent',
     'associative', 'associable', 'nonassociative', 'attached', 'bespoken', 'intended', 'involved', 'unattached',
     'unengaged', 'affixed', 'appendant', 'basifixed', 'glued', 'mounted', 'unaffixed', 'sessile', 'pedunculate',
     'sessile', 'vagile', 'freeSwimming', 'attached', 'detached', 'freestanding', 'semidetached', 'stuck', 'cragfast',
     'unstuck', 'attachable', 'bindable', 'clipOn', 'tieOn', 'detachable', 'clastic', 'wary', 'onGuard', 'shy',
     'unwary', 'gullible', 'unguarded', 'attentive', 'captive', 'advertent', 'observant', 'oversolicitous',
     'solicitous', 'inattentive', 'absent', 'distracted', 'dreamy', 'drowsy', 'forgetful', 'attractive', 'bewitching',
     'charismatic', 'cunning', 'dinky', 'engaging', 'fetching', 'glossy', 'hypnotic', 'irresistible', 'personable',
     'photogenic', 'prepossessing', 'winsome', 'unattractive', 'homely', 'subfusc', 'unprepossessing', 'attractive',
     'repulsive', 'appealing', 'attentionGetting', 'attractive', 'unappealing', 'offPutting', 'unattractive',
     'attributable', 'ascribable', 'credited', 'traceable', 'unattributable', 'attributive', 'attributiveGenitive',
     'predicative', 'pregnant', 'big', 'nonpregnant', 'audible', 'clunky', 'sonic', 'sounding', 'inaudible', 'breathed',
     'infrasonic', 'silent', 'silent', 'supersonic', 'unheard', 'sonic', 'subsonic', 'supersonic', 'auspicious',
     'bright', 'fortunate', 'inauspicious', 'unpromising', 'propitious', 'golden', 'gracious', 'unpropitious', 'ill',
     'thunderous', 'authorized', 'accredited', 'approved', 'canonized', 'empowered', 'unauthorized', 'selfAppointed',
     'unaccredited', 'constitutional', 'unconstitutional', 'autochthonous', 'allochthonous', 'autoecious',
     'heteroecious', 'autogenous', 'selfGenerated', 'selfInduced', 'heterogenous', 'automatic', 'autoloading',
     'automated', 'selfActing', 'selfLocking', 'selfWinding', 'semiautomatic', 'smart', 'manual', 'handOperated',
     'available', 'accessible', 'acquirable', 'addressable', 'easy', 'forthcoming', 'gettable', 'inStock', 'lendable',
     'visible', 'onHand', 'onTap', 'onTap', 'open', 'purchasable', 'ready', 'unavailable', 'inaccessible', 'outOfStock',
     'awake', 'astir', 'awakened', 'insomniac', 'unsleeping', 'waking', 'asleep', 'atRest', 'dormant', 'drowsy',
     'fastAsleep', 'hypnoid', 'sleepy', 'slumberous', 'unawakened', 'astringent')
a_1 = ('styptic', 'nonastringent', 'aware', 'alert', 'conscious', 'sensible', 'unaware', 'oblivious', 'unconscious',
       'unsuspecting', 'witting', 'unwitting', 'alarming', 'appalling', 'atrocious', 'awful', 'baleful',
       'bloodcurdling', 'chilling', 'creepy', 'formidable', 'ghastly', 'hairy', 'petrifying', 'stupefying', 'terrific',
       'unalarming', 'anemophilous', 'entomophilous', 'reassuring', 'assuasive', 'assuring', 'comforting',
       'unreassuring', 'back', 'backmost', 'rear', 'front', 'advance', 'foremost', 'frontal', 'leading', 'directing',
       'guiding', 'following', 'pursuing', 'backed', 'hardbacked', 'highBacked', 'lowBacked', 'razorback',
       'spinyBacked', 'stiffBacked', 'straightBacked', 'backless', 'lowCut', 'backward', 'backswept', 'cacuminal',
       'converse', 'inverse', 'rearward', 'receding', 'reflexive', 'regardant', 'retracted', 'retral', 'retroflex',
       'returning', 'forward', 'guardant', 'headfirst', 'forward', 'reverse', 'backward', 'bashful', 'forward', 'brash',
       'bumptious', 'overfamiliar', 'fresh', 'assumptive', 'balconied', 'unbalconied', 'barreled', 'unbarreled',
       'beaked', 'beaklike', 'billed', 'duckbill', 'rostrate', 'shortBeaked', 'stoutBilled', 'straightBilled',
       'thickBilled', 'beakless', 'bedded', 'doubleBedded', 'singleBedded', 'twinBedded', 'bedless', 'beneficed',
       'unbeneficed', 'stratified', 'foliate', 'laminar', 'layered', 'sheetlike', 'unstratified', 'ferned', 'braky',
       'fernlike', 'fernless', 'grassy', 'grassCovered', 'grasslike', 'rushlike', 'sedgy', 'grassless', 'gusseted',
       'ungusseted', 'hairless', 'bald', 'balding', 'beardless', 'depilatory', 'depilous', 'glabrescent', 'glabrous',
       'nakedMuzzled', 'nakedTailed', 'nonhairy', 'tonsured', 'hairy', 'canescent', 'coarseHaired', 'comate',
       'curlyHaired', 'darkHaired', 'downy', 'floccose', 'furlike', 'furred', 'fuzzed', 'glossyHaired', 'hispid',
       'lanate', 'longHaired', 'pappose', 'pilous', 'roughHaired', 'shockHeaded', 'shortHaired', 'silkyHaired',
       'silverHaired', 'smoothHaired', 'snakeHaired', 'softHaired', 'stiffHaired', 'thickHaired', 'tomentose',
       'velvetyFurred', 'wireHaired', 'wiry', 'wooly', 'awned', 'bearded', 'awnless', 'bearing', 'loadBearing',
       'nonbearing', 'beautiful', 'beauteous', 'bonny', 'dishy', 'exquisite', 'fineLooking', 'glorious', 'gorgeous',
       'lovely', 'picturesque', 'pretty', 'prettyPretty', 'pulchritudinous', 'ravishing', 'scenic', 'stunning', 'ugly',
       'disfigured', 'evilLooking', 'fugly', 'grotesque', 'hideous', 'illFavored', 'scrofulous', 'unlovely',
       'unsightly', 'bellied', 'bigBellied', 'bellyless', 'banded', 'unbanded', 'belted', 'banded', 'beltFed',
       'beltlike', 'unbelted', 'beneficent', 'benefic', 'maleficent', 'baleful', 'malefic', 'malicious', 'despiteful',
       'leering', 'malevolent', 'beadyEyed', 'bitchy', 'poisonous', 'venomed', 'vixenish', 'unmalicious', 'benign',
       'kindly', 'malign', 'cancerous', 'best', 'champion', 'highGrade', 'first', 'goToMeeting', 'optimum', 'primo',
       'recordBreaking', 'secondBest', 'superfine', 'unexcelled', 'unsurpassable', 'worst', 'bottom', 'last',
       'pessimal', 'better', 'amended', 'finer', 'improved', 'worse', 'worsened', 'better', 'fitter', 'worse',
       'bettering', 'ameliorating', 'amendatory', 'corrective', 'remedial', 'worsening', 'bicameral', 'unicameral',
       'bidirectional', 'biface', 'duplex', 'twoWay', 'unidirectional', 'oneWay', 'simplex', 'unifacial', 'faced',
       'babyFaced', 'baldFaced', 'featured', 'JanusFaced', 'longFaced', 'moonFaced', 'paleFaced', 'pugFaced',
       'sadFaced', 'sweetFaced', 'visaged', 'faceless', 'anonymous', 'bibbed', 'bibless', 'unilateral', 'oneParty',
       'multilateral', 'bilateral', 'deepLobed', 'twoLobed', 'bipartite', 'joint', 'multipartite', 'quadrilateral',
       'fiveSided', 'sixSided', 'sevenSided', 'eightSided', 'nineSided', 'tenSided', 'elevenSided', 'twelveSided',
       'quadripartite', 'tetramerous', 'threeCornered', 'threeLobed', 'fourLobed', 'fiveLobed', 'manyLobed',
       'palmatelyLobed', 'trilateral', 'tripartite', 'bimodal', 'unimodal', 'binaural', 'twoEared', 'stereophonic',
       'monaural', 'oneEared', 'mono', 'binucleate', 'mononuclear', 'trinucleate', 'bipedal', 'quadrupedal', 'black',
       'AfricanAmerican', 'colored', 'negro', 'negroid', 'white', 'Caucasian', 'lightSkinned', 'blond', 'ashBlonde',
       'fair', 'flaxen', 'nordic', 'redheaded', 'brunet', 'adust', 'bronzed', 'brown', 'dark', 'darkHaired',
       'darkSkinned', 'grizzled', 'nutbrown', 'blemished', 'acned', 'blebbed', 'blotchy', 'flyblown', 'marred',
       'pocked', 'unblemished', 'stainless', 'bloody', 'bloodFilled', 'bloodstained', 'bloodsucking', 'bloodthirsty',
       'crimson', 'homicidal', 'gory', 'internecine', 'bloodless', 'nonviolent', 'bold', 'audacious', 'daredevil',
       'emboldened', 'foolhardy', 'heroic', 'nervy', 'overreaching', 'overvaliant', 'timid', 'bashful', 'coy',
       'fearful', 'intimidated', 'mousy', 'bound', 'chained', 'fettered', 'furled', 'pinioned', 'tethered', 'trussed',
       'wired', 'unbound', 'unchained', 'untethered', 'laced', 'unlaced', 'tied', 'knotted', 'untied', 'tangled',
       'afoul', 'enmeshed', 'entangled', 'knotty', 'matted', 'rootbound', 'thrown', 'untangled', 'disentangled',
       'bound', 'brassbound', 'cased', 'halfBound', 'paperback', 'wellBound', 'unbound', 'looseleaf', 'bordered',
       'boxed', 'deckled', 'edged', 'fringed', 'lined', 'sawtoothedEdged', 'seagirt', 'spinyEdged', 'whiteEdged',
       'unbordered', 'lotic', 'lentic', 'lowerClass', 'nonU', 'proletarian', 'propertyless', 'upperLowerClass',
       'middleClass', 'bourgeois', 'bourgeois', 'lowerMiddleClass', 'upperMiddleClass', 'upperClass', 'quality',
       'propertied', 'u', 'tweedy', 'wellborn', 'brachycephalic', 'broadHeaded', 'bulletHeaded', 'dolichocephalic',
       'longHeaded', 'brave', 'desperate', 'gallant', 'game', 'lionhearted', 'stalwart', 'undaunted', 'valiant',
       'cowardly', 'caitiff', 'chicken', 'craven', 'dastard', 'faint', 'funky', 'poltroon', 'pusillanimous', 'gutsy',
       'gutless', 'breastFed', 'nursed', 'bottleFed', 'breathing', 'sweetBreathed', 'breathless', 'asphyxiating',
       'smothering', 'blown', 'crystalline', 'crystallized', 'microcrystalline', 'polycrystalline', 'noncrystalline',
       'amorphous', 'landed', 'landless', 'light', 'ablaze', 'autofluorescent', 'bioluminescent', 'bright',
       'candescent', 'floodlit', 'fluorescent', 'illuminated', 'incandescent', 'lamplit', 'lightingUp', 'livid',
       'luminescent', 'phosphorescent', 'sunlit', 'white', 'dark', 'Acheronian', 'aphotic', 'black', 'caliginous',
       'Cimmerian', 'crepuscular', 'darkened', 'darkening', 'darkling', 'darkling', 'dim', 'dusky', 'glooming',
       'lightless', 'semidark', 'tenebrous', 'shaded', 'murky',
       'shady', 'unshaded', 'unshadowed', 'shaded', 'hatched', 'unshaded', 'moonlit', 'moonless', 'bridgeable',
       'unbridgeable', 'bright', 'agleam', 'aglow', 'aglitter', 'beady', 'beaming', 'blazing', 'brightAsANewPenny',
       'brilliant', 'ardent', 'glimmery', 'glistening', 'iridescent', 'lurid', 'noctilucent', 'satiny', 'selfLuminous',
       'shimmery', 'silver', 'twinkling', 'dull', 'flat', 'lackluster', 'soft', 'dimmed', 'lowBeam', 'undimmed',
       'prejudiced', 'homophobic', 'jaundiced', 'loaded', 'racist', 'sexist', 'unprejudiced', 'colorBlind',
       'broadMinded', 'broad', 'catholic', 'freeThinking', 'openMinded', 'narrowMinded', 'closeMinded', 'dogmatic',
       'illiberal', 'opinionated', 'petty', 'reconstructed', 'unreconstructed', 'broken', 'unbroken', 'broken',
       'unbroken', 'broken', 'brokenField', 'dashed', 'fitful', 'halting', 'unbroken', 'solid', 'uninterrupted',
       'brotherly', 'sisterly', 'exergonic', 'endergonic', 'fraternal', 'identical', 'buried', 'belowground',
       'unburied', 'busy', 'atWork', 'drudging', 'engaged', 'overbusy', 'tiedUp', 'upTo', 'idle', 'boneIdle',
       'faineant', 'lackadaisical', 'leisured', 'unengaged', 'bony', 'bone', 'boned', 'bonelike', 'strongBoned',
       'boneless', 'boned', 'buttoned', 'botonee', 'buttonDown', 'unbuttoned', 'openCollared', 'capitalistic',
       'bourgeois', 'competitive', 'individualistic', 'socialistic', 'collective', 'collectivist', 'cacophonous',
       'cackly', 'croaky', 'grating', 'gruff', 'jangling', 'jarring', 'raucous', 'rending', 'euphonious', 'golden',
       'silvern', 'calculable', 'computable', 'countable', 'incalculable', 'countless', 'incomputable',
       'indeterminable', 'calm', 'placid', 'settled', 'windless', 'stormy', 'angry', 'billowy', 'blustering',
       'boisterous', 'blowy', 'choppy', 'dirty', 'gusty', 'squally', 'thundery', 'camphorated', 'uncamphorated',
       'capable', 'able', 'confident', 'resourceful', 'incapable', 'unable', 'capable', 'incapable', 'caredFor',
       'attended', 'uncaredFor', 'neglected', 'untended', 'careful', 'blowByBlow', 'certain', 'close', 'conscientious',
       'detailed', 'minute', 'overcareful', 'particular', 'protective', 'studious', 'thorough', 'careless', 'casual',
       'haphazard', 'heedless', 'incautious', 'offhand', 'carnivorous', 'fleshEating', 'piscivorous', 'predacious',
       'herbivorous', 'anthophagous', 'baccivorous', 'carpophagous', 'grassEating', 'plantEating', 'saprophagous',
       'saprophytic', 'omnivorous', 'allDevouring', 'insectivorous', 'apivorous', 'myrmecophagous', 'holozoic',
       'holophytic', 'carpellate', 'acarpelous', 'carpeted', 'uncarpeted', 'carvelBuilt', 'flushSeamed', 'clinkerBuilt',
       'carved', 'engraved', 'graven', 'lapidarian', 'sliced', 'uncarved', 'acatalectic', 'catalectic',
       'hypercatalectic', 'cauline', 'radical', 'censored', 'expurgated', 'uncensored', 'unexpurgated', 'caudate',
       'bobtail', 'caudal', 'tailed', 'scalyTailed', 'scissorTailed', 'shortTailed', 'squareTailed', 'stiffTailed',
       'swallowTailed', 'tailShaped', 'acaudate', 'anurous', 'caulescent', 'cylindricalStemmed', 'leafyStemmed',
       'multiStemmed', 'shortStemmed', 'spinyStemmed', 'stoutStemmed', 'thickStemmed', 'weakStemmed', 'wiryStemmed',
       'woollyStemmed', 'woodyStemmed', 'acaulescent', 'causative', 'abortifacient', 'activating', 'anorectic',
       'causal', 'conducive', 'errhine', 'fast', 'inductive', 'motivative', 'motive', 'precipitating', 'responsible',
       'sternutatory', 'noncausative', 'cautious', 'cagey', 'fabian', 'gingerly', 'guarded', 'overcautious',
       'incautious', 'hotheaded', 'cellular', 'cancellate', 'alveolate', 'cellLike', 'lymphoblastLike', 'multicellular',
       'noncellular', 'cellFree', 'singleCelled', 'coherent', 'incoherent', 'compartmented', 'compartmental',
       'uncompartmented', 'porous', 'porose', 'nonporous', 'central', 'amidship', 'bicentric', 'bifocal', 'center',
       'centered', 'centric', 'focal', 'median', 'middlemost', 'nuclear', 'peripheral', 'circumferential', 'fringy',
       'encircling', 'offBase', 'centrifugal', 'outwardDeveloping', 'outwardMoving', 'centripetal', 'inwardDeveloping',
       'inwardMoving', 'afferent', 'centripetal', 'corticoafferent', 'efferent', 'centrifugal', 'corticoefferent',
       'neuromotor', 'centralizing', 'centripetal', 'consolidative', 'decentralizing', 'centrifugal', 'certain',
       'definite', 'indisputable', 'sureAsShooting', 'uncertain', 'indefinite', 'upInTheAir', 'certain', 'convinced',
       'uncertain', 'ambivalent', 'doubtful', 'groping', 'convinced', 'unconvinced', 'dubious', 'confident', 'assured',
       'cocksure', 'reassured', 'selfAssured', 'diffident', 'certain', 'bound', 'doomed', 'foreordained', 'inFor',
       'uncertain', 'chancy', 'contingent', 'upInTheAir', 'certified', 'certifiable', 'certificated', 'credentialled',
       'uncertified', 'inevitable', 'fatal', 'ineluctable', 'necessary', 'evitable', 'preventable', 'unpreventable',
       'changeable', 'adjustable', 'astatic', 'checkered', 'distortable', 'erratic', 'fluid', 'fluid', 'jittering',
       'kaleidoscopic', 'mobile', 'openEnded', 'quickChange', 'quickDrying', 'reversible', 'volatile', 'unchangeable',
       'changeless', 'confirmed', 'fixed', 'setInStone', 'static', 'commutable', 'alterable', 'convertible',
       'incommutable', 'inconvertible', 'unalterable', 'alterable', 'unalterable', 'incurable', 'final', 'modifiable',
       'unmodifiable', 'adjusted', 'focused', 'weighted', 'unadjusted', 'maladjusted', 'adjusted', 'wellAdjusted',
       'maladjusted', 'unadapted', 'altered', 'adjusted', 'changed', 'emended', 'paraphrastic', 'revised', 'unaltered',
       'dateless', 'inSitu', 'unedited', 'unreduced', 'unrevised', 'amended', 'revised', 'unamended', 'changed',
       'denatured', 'exchanged', 'transformed', 'varied', 'unchanged', 'idempotent', 'same', 'isometric', 'isotonic',
       'ionized', 'nonionized', 'mutable', 'immutable', 'characteristic', 'diagnostic', 'distinctive', 'peculiar',
       'uncharacteristic', 'charged', 'hot', 'negative', 'positive', 'polar', 'uncharged', 'neutral', 'dead',
       'charitable', 'beneficent', 'uncharitable', 'chartered', 'unchartered', 'owned', 'closelyHeld', 'unowned',
       'chaste', 'celibate', 'pure', 'unchaste', 'cyprian', 'easy', 'fallen', 'licentious', 'cheerful', 'beaming',
       'beamish', 'blithe', 'buoyant', 'cheery', 'chipper', 'depressing', 'blue', 'somber', 'chlamydeous',
       'achlamydeous', 'chondritic', 'achondritic', 'monoclinic', 'triclinic', 'monochromatic', 'polychromatic',
       'chromatic', 'amber', 'amberGreen', 'amethyst', 'auburn', 'aureate', 'avocado', 'azure', 'beige',
       'blackishBrown', 'blackishRed', 'blae', 'blue', 'bluishGreen', 'blueLilac', 'bluePurple', 'blueViolet',
       'blushful', 'bottleGreen', 'brightRed', 'bronze')
n = (
'entity', 'physicalEntity', 'abstraction', 'thing', 'object', 'whole', 'congener', 'livingThing', 'organism', 'benthos',
'dwarf', 'heterotroph', 'parent', 'life', 'biont', 'cell', 'causalAgent', 'person', 'animal', 'plant', 'native',
'naturalObject', 'substance', 'substance', 'matter', 'food', 'nutrient', 'artifact', 'article', 'psychologicalFeature',
'cognition', 'motivation', 'attribute', 'state', 'feeling', 'location', 'shape', 'time', 'space', 'absoluteSpace',
'phaseSpace', 'event', 'process', 'act', 'group', 'relation', 'possession', 'socialRelation', 'communication',
'measure', 'phenomenon', 'thing', 'kindness', 'abdominoplasty', 'abort', 'accomplishment', 'agon', 'alienation',
'application', 'beachhead', 'cakewalk', 'feat', 'masterpiece', 'masterstroke', 'credit', 'action', 'resGestae',
'course', 'blindAlley', 'collisionCourse', 'interaction', 'interplay', 'contact', 'brush', 'eyeContact', 'fetch',
'placement', 'interchange', 'reciprocity', 'crossFertilization', 'dealings', 'relation', 'playing', 'play',
'boondoggle', 'bowling', 'acquiring', 'causing', 'delivery', 'departure', 'derringDo', 'discovery', 'disposal', 'hit',
'implementation', 'egress', 'equalization', 'exhumation', 'mitzvah', 'propulsion', 'rally', 'recovery', 'runningAway',
'stunt', 'touch', 'tourDeForce', 'performance', 'overachievement', 'underachievement', 'record', 'faitAccompli',
'going', 'arrival', 'arrival', 'attainment', 'advent', 'entrance', 'incursion', 'intrusion', 'irruption', 'entree',
'entail', 'registration', 'appearance', 'apparition', 'emergence', 'reappearance', 'comeback', 'return', 'repatriation',
'penetration', 'interpenetration', 'marketPenetration', 'anchorage', 'docking', 'landing', 'landing', 'forcedLanding',
'breakingAway', 'farewell', 'FrenchLeave', 'valediction', 'disappearance', 'vanishing', 'withdrawal', 'effacement',
'retreat', 'retirement', 'evacuation', 'medicalEvacuation', 'decampment', 'desertion', 'abscondment',
'absenceWithoutLeave', 'deviationism', 'emigration', 'immigration', 'aliyah', 'pullback', 'retreat', 'standdown',
'disengagement', 'receding', 'sailing', 'amphibiousLanding', 'debarkation', 'goingAshore', 'boarding', 'exit',
'elopement', 'escape', 'evasion', 'slip', 'maneuver', 'clinch', 'dodge', 'break', 'getaway', 'exodus', 'Hegira',
'skedaddle', 'UndergroundRailroad', 'closeCall', 'surfacing', 'dispatch', 'reshipment', 'consummation', 'consummation',
'realization', 'orgasm', 'maleOrgasm', 'fulfillment', 'selfFulfillment', 'attainment', 'record', 'trackRecord',
'worldRecord', 'success', 'winning', 'blockbuster', 'sleeper', 'hit', 'bellRinger', 'ennoblement', 'conquest', 'coup',
'flyingColors', 'passing', 'credit', 'semesterHour', 'nonaccomplishment', 'failure', 'failure', 'failing', 'naught',
'cut', 'default', 'loss', 'capitulation', 'frustration', 'overturn', 'backsliding', 'recidivism', 'disappointment',
'breach', 'copout', 'breachOfContract', 'anticipatoryBreach', 'breachOfDuty', 'breachOfTheCovenantOfWarranty',
'breachOfPromise', 'breachOfTrust', 'breachOfTrustWithFraudulentIntent', 'breachOfWarranty', 'leaning',
'materialBreach', 'motivation', 'partialBreach', 'mistake', 'doubleFault', 'footfault', 'bobble', 'error', 'blot',
'confusion', 'incursion', 'miscalculation', 'backfire', 'rounding', 'truncationError', 'distortion', 'slip',
'FreudianSlip', 'offside', 'oversight', 'omission', 'blunder', 'snafu', 'spectacle', 'ballup', 'bull', 'fumble',
'fluff', 'fauxPas', 'howler', 'clanger', 'trip', 'spill', 'pratfall', 'wipeout', 'acquisition', 'obtainment',
'catching', 'incurring', 'moneymaking', 'annexation', 'porkBarreling', 'purchase', 'redemption', 'trading',
'bondTrading', 'programTrading', 'shortSale', 'shortCovering', 'insiderTrading', 'nakedOption', 'coveredOption',
'callOption', 'putOption', 'straddle', 'incentiveOption', 'buying', 'shopping', 'marketing', 'mailOrderBuying',
'viatication', 'acceptance', 'succession', 'assumption', 'assumption', 'position', 'inheritance', 'procurement',
'appropriation', 'borrowing', 'naturalization', 'misappropriation', 'preemption', 'seizure', 'usurpation',
'confiscation', 'distress', 'expropriation', 'impoundment', 'drugBust', 'impress', 'occupation', 'preoccupancy',
'sequestration', 'grant', 'award', 'addiction', 'blockGrant', 'grantInAid', 'capture', 'apprehension', 'conquest',
'enslavement', 'restitution', 'clawback', 'repossession', 'foreclosure', 'reception', 'appointment', 'combOut',
'giving', 'abandonment', 'discard', 'staging', 'discard', 'mineDisposal', 'minesweeping', 'sewageDisposal',
'baitAndSwitch', 'privateTreaty', 'auction', 'bootlegging', 'bootlegging', 'capitalization', 'overcapitalization',
'reclamation', 'rescue', 'lifesaving', 'redemption', 'absolution', 'indulgence', 'conversion', 'proselytism',
'expiation', 'reparation', 'liberation', 'jailDelivery', 'reclamation', 'salvage', 'salvage', 'salvation',
'searchAndRescueMission', 'ransom', 'recapture', 'recapture', 'invocation', 'instrumentation', 'performance',
'specificPerformance', 'linguisticPerformance', 'mechanism', 'service', 'curbService', 'selfService', 'valetParking',
'dramaticProduction', 'encore', 'extemporization', 'juggle', 'magicTrick', 'musicalPerformance', 'oneNightStand',
'rendition', 'reinterpretation', 'spin', 'playing', 'bowing', 'spiccato', 'piping', 'stopping', 'doubleStopping',
'transposition', 'jamSession', 'automation', 'computerization', 'motorization', 'launching', 'launching',
'rocketFiring', 'blastoff', 'moonShot', 'drive', 'firewall', 'impulse', 'roll', 'throw', 'bowling', 'fling', 'heave',
'hurl', 'leaner', 'pass', 'pitch', 'pitch', 'ringer', 'shy', 'slinging', 'throwIn', 'balk', 'ball', 'beanball',
'changeUp', 'curve', 'duster', 'fastball', 'knuckleball', 'overhandPitch', 'passedBall', 'screwball', 'sinker',
'slider', 'spitball', 'strike', 'submarineBall', 'wildPitch', 'basketballShot', 'bankShot', 'dunk', 'slamDunk',
'fingerRoll', 'foulShot', 'oneAndOne', 'hookShot', 'jumper', 'layUp', 'pivotShot', 'setShot', 'scoopShot', 'tipIn',
'push', 'depression', 'click', 'nudge', 'press', 'impression', 'shove', 'bundling', 'jostle', 'elbowing', 'pull',
'drag', 'draw', 'tow', 'tug', 'draft', 'extirpation', 'pluck', 'traction', 'lift', 'expulsion', 'defenestration',
'accommodationReflex', 'Babinski', 'belch', 'belching', 'blink', 'blush', 'coughingUp', 'spit', 'vomit', 'rumination',
'hematemesis', 'hyperemesis', 'hyperemesisGravidarum', 'jump', 'header', 'hop', 'leap', 'vault', 'jumpingUpAndDown',
'lob', 'centering', 'sending', 'transmission', 'forwarding', 'referral', 'remission', 'mailing', 'wheeling', 'shooting',
'shoot', 'countershot', 'discharge', 'gun', 'fireControl', 'gunfire', 'enfilade', 'snipe', 'headshot', 'skeet',
'shellfire', 'gunfight', 'potshot',
'contact', 'rub', 'scuff', 'tap', 'hit', 'contusion', 'crash', 'impingement', 'batting', 'fielding', 'catching',
'golfing', 'pitching', 'baseOnBalls', 'best', 'worst', 'fairBall', 'foulBall', 'snick', 'bunt', 'fly', 'blast',
'popFly', 'grounder', 'chop', 'roller', 'out', 'forceOut', 'putout', 'strikeout', 'whiff', "fielder'sChoice",
'sacrifice', 'sacrificeFly', 'baseHit', 'daisyCutter', 'header', 'liner', 'scorcher', 'lineDriveSingle',
'lineDriveDouble', 'lineDriveTriple', 'plunk', 'homer', 'soloHomer', 'single', 'double', 'triple', 'backhander', 'clip',
'knock', 'thwack', 'smack', 'smacker', 'knockdown', 'knockout', 'technicalKnockout', 'swat', 'spank', 'whip', 'punch',
'box', 'dig', 'counterpunch', 'haymaker', 'hook', 'jab', 'rabbitPunch', 'suckerPunch', 'roundhouse', 'kick', 'goalKick',
'goalKick', 'punt', 'placeKick', 'freeKick', 'cornerKick', 'dropkick', 'kiss', 'kiss', 'layingOn', 'smack', 'smacker',
'soulKiss', 'catch', 'fairCatch', 'interception', 'reception', 'rebound', 'shoestringCatch', 'mesh', 'handling',
'fingering', 'grope', 'audit', 'autopsy', 'checkIn', 'check', 'spotCheck', 'checkup', 'comparison', 'fineToothComb',
'followUp', 'goingOver', 'onceOver', 'ophthalmoscopy', 'palpation', 'ballottement', 'tickle', 'stroke', 'caress', 'tag',
'joining', 'hit', 'interconnection', 'intersection', 'approximation', 'concatenation', 'convergence', 'merging',
'concourse', 'encounter', 'articulation', 'junction', 'fastening', 'loosening', 'tightening', 'ligation',
'tubalLigation', 'bonding', 'doweling', 'grounding', 'linkage', 'tying', 'untying', 'welding', 'buttWelding',
'spotWelding', 'flare', 'TexasLeaguer', 'flashWelding', 'lick', 'grazing', 'tracing', 'detection', 'selfDiscovery',
'breakthrough', 'determination', 'rediscovery', 'designation', 'BertillonSystem', 'fingerprinting', 'geneticProfiling',
'diagnosis', 'bloodTyping', 'medicalDiagnosis', 'prenatalDiagnosis', 'differentialDiagnosis', 'prognosis', 'resolution',
'validation', 'authentication', 'documentation', 'monetization', 'probate', 'demonetization', 'falsification',
'localization', 'echolocation', 'predetermination', 'rectification', 'redetermination', 'trigger', 'fomentation',
'compulsion', 'influence', 'crossPollination', 'exposure', 'overexposure', 'underexposure', 'impingement',
'manipulation', 'mindGame', 'autosuggestion', 'hypnotism', 'inducement', 'corruption', 'enticement', 'blandishment',
'ingratiation', 'leadingAstray', 'seduction', 'seduction', 'sexualConquest', 'cuckoldry', 'solicitation', 'choice',
'casting', 'coloration', 'sampling', 'randomSampling', 'luckyDip', 'stratifiedSampling', 'decision', 'volition',
'intention', 'aboutFace', 'adulteration', 'appointment', 'nomination', 'assignment', 'allocation', 'call', 'coOption',
'delegacy', 'ordination', 'recognition', 'layingOnOfHands', 'move', 'move', 'chessMove', 'castle', 'capture',
'enPassant', 'exchange', 'exchange', 'check', 'discoveredCheck', 'checkmate', 'gambit', 'demarche', 'maneuver',
'parking', 'move', 'flit', 'downshift', 'downshift', 'bank', 'verticalBank', 'chandelle', 'loop', 'insideLoop',
'outsideLoop', 'roll', 'barrelRoll', 'snapRoll', 'slip', 'flightManeuver', 'straightArm', 'device', 'mnemonic', 'trick',
'shtik', 'feint', 'juke', 'footwork', 'ploy', 'ruse', 'means', 'dint', 'escape', 'fastTrack', 'instrument', 'road',
'royalRoad', 'steppingStone', 'measure', 'countermeasure', 'bearHug', 'proxyFight', 'leveragedBuyout', 'bustUpTakeover',
'sharkRepellent', 'goldenParachute', 'greenmail', 'pacManStrategy', 'poisonPill', 'suicidePill', 'safeHarbor',
'scorchedEarthPolicy', 'diagnosticProcedure', 'expedient', 'backstop', 'emergencyProcedure', 'experimentalProcedure',
'doubleBlindProcedure', 'makeshift', 'crutch', 'improvisation', 'pisAller', 'desperateMeasure', 'openSesame',
'salvation', 'tooth', 'voice', 'wings', 'castingLots', 'resolution', 'adoption', 'embrace', 'election', 'coOption',
'reelection', 'plebiscite', 'referendum', 'election', 'vote', 'generalElection', 'primary', 'directPrimary',
'closedPrimary', 'openPrimary', 'byElection', 'runoff', 'vote', 'blockVote', 'cumulativeVote', 'secretBallot',
'splitTicket', 'straightTicket', 'multipleVoting', 'castingVote', 'reconciliation', 'equation', 'breechDelivery',
'frankBreech', 'cesareanDelivery', 'forcepsDelivery', 'midwifery', 'score', 'bowlingScore', "bull'sEye", 'goal',
'ownGoal', 'strike', 'spare', 'openFrame', 'audible', 'footballScore', 'touchback', 'safety', 'touchdown', 'fieldGoal',
'conversion', 'pointAfter', 'baseballScore', 'run', 'earnedRun', 'unearnedRun', 'runBattedIn', 'basketballScore',
'basket', 'hatTrick', 'solution', 'RussianRoulette', 'change', 'filtration', 'percolation', 'reduction',
'schematization', 'economy', 'retrenchment', 'economyOfScale', 'accommodation', 'adaptation', 'darkAdaptation',
'lightAdaptation', 'takeUp', 'readjustment', 'domestication', 'decimalization', 'metrification', 'habituation',
'variation', 'variation', 'turning', 'diversification', 'flux', 'switch', 'switcheroo', 'substitution', 'novation',
'pitchingChange', 'superannuation', 'supersedure', 'supplanting', 'replacement', 'subrogation', 'weaning', 'promotion',
'preferment', 'demotion', 'investment', 'changeOfState', 'alteration', 'distraction', 'aeration', 'modulation',
'qualification', 'reorganization', 'passage', 'fossilization', 'segue', 'meddling', 'transfer', 'prohibition',
'resistance', 'lockout', 'reaction', 'backlash', 'whitelash', 'rejection', 'brushOff', 'avoidance', 'aversion',
'escape', 'nearThing', 'abandonment', 'exposure', 'apostasy', 'bolt', 'renunciation', 'nonacceptance', 'forsaking',
'abnegation', 'forfeit', 'boycott', 'banishment', 'anathematization', 'disbarment', 'ejection', 'deportation',
'ostracism', 'barring', 'exile', 'BabylonianCaptivity', 'excommunication', 'relegation', 'rustication', 'ouster',
'deposition', 'suspension', 'rustication', 'displacement', 'veto', 'pocketVeto', 'writeIn', 'termination', 'finish',
'finale', 'release', 'completion', 'finalization', 'followThrough', 'followThrough', 'graduation', 'retirement',
'hibernation', 'rustication', 'swanSong', 'relinquishment', 'cession', 'handover', 'surrender', 'extradition',
'release', 'exemption', 'fix', 'officialImmunity', 'sovereignImmunity', 'transactionalImmunity', 'useImmunity',
'dissolution', 'splitsville', 'overthrow', 'subversion', 'adjournment', 'dismissal', 'conge', 'removal', 'purge',
'destruction', 'disaster', 'kill', 'layingWaste', 'razing', 'annihilation', 'decimation', 'atomization',
'pulverization', 'vaporization', 'killing', 'deathblow', 'death', 'driveByKilling', 'euthanasia', 'homicide',
'honorKilling', 'manslaughter', 'murder', 'assassination', 'bloodshed', 'chanceMedley', 'contractKilling', 'parricide',
'mariticide')
