# Generated by Django 2.2.1 on 2019-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shortlink',
            field=models.CharField(max_length=400),
        ),
    ]
