# Generated by Django 2.2.2 on 2019-06-08 14:27

from django.db import migrations

from urlshort.util import urldigest


def populate_urlhash(apps, _):
    ShortUrl = apps.get_model('urlshort', 'ShortUrl')
    for surl in ShortUrl.objects.all():
        surl.urlhash = urldigest(surl.url)
        surl.save()


class Migration(migrations.Migration):
    dependencies = [
        ('urlshort', '0004_shorturl_urlhash'),
    ]

    operations = [
        migrations.RunPython(populate_urlhash)
    ]
