# Generated by Django 2.2.2 on 2019-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0005_auto_20190608_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='urlhash',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
